### ISSUE TITLE
The callbacks in the test functions are called regardless of the result of tryingToClone

### ISSUE THREAD

**Issue by jdm** [OODD-Mozilla/ToolRepository#10]
The test functions currently do not demonstrate whether cloning was successful or not, because the callback is always executed as soon as the clone operations have begun. It would be better to return the Promise object from tryingToClone and using operations like Promise.all to chain the callback to the successful execution of all of the clone operations.

**Comment by kbrey** [comment]
Testing approach has changed and this is no longer applicable.
