### ISSUE TITLE
Tools/commands for subsequent steps

### ISSUE THREAD

**Issue by sshankjha** [OODD-Mozilla/ToolRepository#12]
Lets put all the important tools/commands which we find here for discussion:

1. API for pull requests: 
curl -i "https://api.github.com/repos/OODD-Mozilla/oodd-project1-sjha5/pulls"

API to get commit list from pull requests:
https://api.github.com/repos/OODD-Mozilla/oodd-project1-sjha5/pulls/1/commits 

2. To get names of author: 
git log --format='%aN' | sort -u

For checking names/email/date of commiter/authors refer to:
https://git-scm.com/book/en/v2/Git-Basics-Viewing-the-Commit-History
(table 1)

3. For using git from node.js we can use library simple-git:

https://www.npmjs.com/package/simple-git
Description given: A light weight interface for running git commands in any node.js application.

4. For testing:

- Mocha framework (https://mochajs.org/)
- Nock, for mocking (https://www.npmjs.com/package/nock)

**Comment by sshankjha** [comment]
URL for fetching pull request from particular date:

curl -i "https://api.github.com/repos/OODD-Mozilla/oodd-project1-sjha5/pulls?state=closed&sort=closed_at&since=2017-01-01T00:00:00Z"

**Comment by sshankjha** [comment]
Create a tool that processes all of the closed pull requests for a github organization _during a particular time period_
Where is this information coming from?

**Comment by kbrey** [comment]
Alright, I think I'll resolve this since we are done!
