### ISSUE TITLE
getCommitsUrlFromAllPulls gets more inefficient over time

### ISSUE THREAD

**Issue by jdm** [OODD-Mozilla/ToolRepository#19]
It appears to fetch all closed pull requests for a given repository. In the case of Servo, for example, that number is currently [9,720](https://github.com/servo/servo/pulls?q=is%3Apr+is%3Aclosed) and growing by 100+ every week. The original project description included "during a particular time period" for a reason...

**Comment by sshankjha** [comment]
@jdm Github API does not support filtering by date for pull requests directly (unlike issues) 
https://developer.github.com/v3/pulls/
So I have added few lines in getCommitsUrlFromAllPulls to check for date and return only relevant pulls. Please check and let me know if it is good enough.

**Comment by jdm** [comment]
I provided an API that worked for me in the project description. Rather than repository by repository, it queries all of them at once.

**Comment by sshankjha** [comment]
I have changed the code again. Please have a look.

**Comment by jdm** [comment]
That looks like an improvement!
