### ISSUE TITLE
Issues based on round 1 review

### ISSUE THREAD

**Issue by sshankjha** [OODD-Mozilla/ToolRepository#8]
- [x] R1Q1: The description is organized properly and explains what the project is about. _However, I could not understand how the project does what it does._
- [x] R1Q2: The write up mentions some points about how they have implemented the changes, _but it does not give any justification on why the took those steps. It also does not describe any Design Pattern or principles that they followed._ 
- [x] R1Q8: Adding some more comments about what the code does would be really helpful for the people who are looking at the code later.
- [x] R2Q1: .. if there was a background section first on the Expertiza wiki. Just looking at the Expertiza wiki I was confused until I first read the GitHub wiki and then the Expertiza wiki. 
- [x] R2Q3: I also do not understand why authors will not say design patterns do not apply? 
- [x] R4Q2:  But under 'scope' section, they mention that the scope of the project as to 'complete the initial steps mentioned'. Providing an explanation on why the steps were chosen to do and if there were any alternatives could have provided a better explanation.
- [x] R4Q10: The instructions for how to create the API token aren't very clear so wasn't able to get that working.
- [x] R9AC: There is some kind of "Cite error" at the bottom of the wiki page.

**Comment by Nikhila-B** [comment]
1. Mention about pull request | framework and decision choice - why & how ( explanation and justification)
2. Add comments to the code - Author.js
3. Testing
- tests plan >  --- test cases [ edge case]
- how to run the tests description
 - possible screencast?

**Comment by sshankjha** [comment]
@Nikhila-B Added few comments to the code. Add if something is missing.

**Comment by harshalgala** [comment]
Added the background section in the Introduction part.

**Comment by sshankjha** [comment]
Added project description. Included subsequent steps as well for clarity.

**Comment by harshalgala** [comment]
Done with description editing
