### ISSUE TITLE
The github web API only retrieves a limited number of commits

### ISSUE THREAD

**Issue by jdm** [OODD-Mozilla/ToolRepository#9]
For example, https://api.github.com/repos/servo/servo/commits only retrieves the most recent 30 commits. Additionally, the github API has rate limiting enabled, so it can be complex to write a tool that will paginate results and not end up exceeding the limit for large repositories. It would be much less complicated to access a local clone of a repository instead of using the API.

**Comment by kbrey** [comment]
We have implemented AuthorTool.js which looks at commits from local repositories.
